// <auto-generated />
using System;
using Api_One_Trick_Pony_Br.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api_One_Trick_Pony_Br.Migrations
{
    [DbContext(typeof(Api_One_Trick_Pony_BrContext))]
    [Migration("20241225154315_segundamigration")]
    partial class segundamigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api_One_Trick_Pony_Br.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonochampId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonochampId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Api_One_Trick_Pony_Br.Models.Pony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Elo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IconID")
                        .HasColumnType("integer");

                    b.Property<int>("Karma")
                        .HasColumnType("integer");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pdl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pony");
                });

            modelBuilder.Entity("Api_One_Trick_Pony_Br.Models.Comment", b =>
                {
                    b.HasOne("Api_One_Trick_Pony_Br.Models.Pony", "Monochamp")
                        .WithMany("Comments")
                        .HasForeignKey("MonochampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monochamp");
                });

            modelBuilder.Entity("Api_One_Trick_Pony_Br.Models.Pony", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
